// Static continent classification by ISO 3166-1 alpha-2 code, covering current UN member states,
// the two UN observer states this dataset also scrapes (Holy See/Vatican City, Palestine), and a
// handful of states with limited recognition (Taiwan, Kosovo, and the Sahrawi Arab Democratic
// Republic/Western Sahara, coded EH per ISO 3166-1).
// A handful of countries straddle two continents by landmass (Russia, Turkey, Kazakhstan, Georgia,
// Armenia, Azerbaijan, Cyprus); these follow the UN geoscheme convention used by most public datasets.
export const CONTINENT_BY_ISO2: Record<string, string> = {
  AF: 'Asia', AL: 'Europe', DZ: 'Africa', AD: 'Europe', AO: 'Africa', AG: 'North America',
  AR: 'South America', AM: 'Asia', AU: 'Oceania', AT: 'Europe', AZ: 'Asia', BS: 'North America',
  BH: 'Asia', BD: 'Asia', BB: 'North America', BY: 'Europe', BE: 'Europe', BZ: 'North America',
  BJ: 'Africa', BT: 'Asia', BO: 'South America', BA: 'Europe', BW: 'Africa', BR: 'South America',
  BN: 'Asia', BG: 'Europe', BF: 'Africa', BI: 'Africa', KH: 'Asia', CM: 'Africa', CA: 'North America',
  CV: 'Africa', CF: 'Africa', TD: 'Africa', CL: 'South America', CN: 'Asia', CO: 'South America',
  KM: 'Africa', CD: 'Africa', CG: 'Africa', CR: 'North America', HR: 'Europe', CU: 'North America',
  CY: 'Asia', CZ: 'Europe', DK: 'Europe', DJ: 'Africa', DM: 'North America', DO: 'North America',
  EC: 'South America', EG: 'Africa', SV: 'North America', GQ: 'Africa', ER: 'Africa', EE: 'Europe',
  SZ: 'Africa', ET: 'Africa', FJ: 'Oceania', FI: 'Europe', FR: 'Europe', GA: 'Africa', GM: 'Africa',
  GE: 'Asia', DE: 'Europe', GH: 'Africa', GR: 'Europe', GD: 'North America', GT: 'North America',
  GN: 'Africa', GW: 'Africa', GY: 'South America', HT: 'North America', HN: 'North America',
  HU: 'Europe', IS: 'Europe', IN: 'Asia', ID: 'Asia', IR: 'Asia', IQ: 'Asia', IE: 'Europe',
  IL: 'Asia', IT: 'Europe', CI: 'Africa', JM: 'North America', JP: 'Asia', JO: 'Asia', KZ: 'Asia',
  KE: 'Africa', KI: 'Oceania', KW: 'Asia', KG: 'Asia', LA: 'Asia', LV: 'Europe', LB: 'Asia',
  LS: 'Africa', LR: 'Africa', LY: 'Africa', LI: 'Europe', LT: 'Europe', LU: 'Europe', MG: 'Africa',
  MW: 'Africa', MY: 'Asia', MV: 'Asia', ML: 'Africa', MT: 'Europe', MH: 'Oceania', MR: 'Africa',
  MU: 'Africa', MX: 'North America', FM: 'Oceania', MD: 'Europe', MC: 'Europe', MN: 'Asia',
  ME: 'Europe', MA: 'Africa', MZ: 'Africa', MM: 'Asia', NA: 'Africa', NR: 'Oceania', NP: 'Asia',
  NL: 'Europe', NZ: 'Oceania', NI: 'North America', NE: 'Africa', NG: 'Africa', KP: 'Asia',
  MK: 'Europe', NO: 'Europe', OM: 'Asia', PK: 'Asia', PW: 'Oceania', PA: 'North America',
  PG: 'Oceania', PY: 'South America', PE: 'South America', PH: 'Asia', PL: 'Europe', PT: 'Europe',
  PS: 'Asia', QA: 'Asia', RO: 'Europe', RU: 'Europe', RW: 'Africa', KN: 'North America', LC: 'North America',
  VA: 'Europe', VC: 'North America', WS: 'Oceania', SM: 'Europe', ST: 'Africa', SA: 'Asia', SN: 'Africa',
  TW: 'Asia', EH: 'Africa', XK: 'Europe',
  RS: 'Europe', SC: 'Africa', SL: 'Africa', SG: 'Asia', SK: 'Europe', SI: 'Europe', SB: 'Oceania',
  SO: 'Africa', ZA: 'Africa', KR: 'Asia', SS: 'Africa', ES: 'Europe', LK: 'Asia', SD: 'Africa',
  SR: 'South America', SE: 'Europe', CH: 'Europe', SY: 'Asia', TJ: 'Asia', TZ: 'Africa',
  TH: 'Asia', TL: 'Asia', TG: 'Africa', TO: 'Oceania', TT: 'North America', TN: 'Africa',
  TR: 'Asia', TM: 'Asia', TV: 'Oceania', UG: 'Africa', UA: 'Europe', AE: 'Asia', GB: 'Europe',
  US: 'North America', UY: 'South America', UZ: 'Asia', VU: 'Oceania', VE: 'South America',
  VN: 'Asia', YE: 'Asia', ZM: 'Africa', ZW: 'Africa',
};
